<Project>
	<PropertyGroup>
		<Authors>Kevin Jump</Authors>
		<Company>Jumoo</Company>

		<PackageTags>umbraco usync</PackageTags>

		<Copyright>Jumoo @ 2024</Copyright>

		<PackageReleaseNotes><![CDATA[15. Management API Release]]></PackageReleaseNotes>
	
		<IncludeSymbols>false</IncludeSymbols>
		<IncludeSymbols>false</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<IncludeBuildOutput>true</IncludeBuildOutput>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>

	</PropertyGroup>
</Project>