<Project>
	<PropertyGroup>
		<Authors>Kevin Jump</Authors>
		<Company>Jumoo</Company>

		<PackageTags>umbraco usync</PackageTags>

		<VersionPrefix>17.0.0</VersionPrefix>

		<Copyright>Jumoo @ 2024-2026</Copyright>

		<PackageReleaseNotes><![CDATA[17. Umbraco 17 release]]></PackageReleaseNotes>

		<IncludeSymbols>false</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<IncludeBuildOutput>true</IncludeBuildOutput>

		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://jumoo.co.uk</PackageProjectUrl>

		<RepositoryUrl>https://github.com/Jumoo/uSync.CommandLine</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>
</Project>
